import fs from 'node:fs';import path from 'node:path';import vm from 'node:vm';import assert from 'node:assert/strict';import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');let required=true,url='https://accounts.google.com/o/oauth2/auth?x=1&y=2';const box={ScriptApp:{AuthMode:{FULL:'FULL'},AuthorizationStatus:{REQUIRED:'REQUIRED'},getAuthorizationInfo:mode=>{assert.equal(mode,'FULL');return {getAuthorizationStatus:()=>required?'REQUIRED':'NOT_REQUIRED',getAuthorizationUrl:()=>url}},getService:()=>({getUrl:()=> 'https://script.google.com/macros/s/TEST/exec'})},Session:{getActiveUser:()=>({getEmail:()=> 'user@shopee.com'})},PORTAL_BACKEND_RELEASE:'4.9.3',escapeHtml_:s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;'),HtmlService:{createHtmlOutput:html=>({html,setTitle(){return this}})}};vm.createContext(box);vm.runInContext(fs.readFileSync(path.join(root,'backend/WorkspaceConsent.gs'),'utf8'),box);
let n=0;function test(label,f){f();n++;console.log('PASS '+label)}
test('Missing consent returns Google authorization page',()=>assert.ok(box.portalSetupConsentGate_().html.includes('accounts.google.com')));
test('Retry retains correct deployment and release',()=>assert.ok(box.portalSetupConsentGate_().html.includes('TEST/exec?action=setup&amp;release=4.9.3')));
test('No authorization bypass when link absent',()=>{url='';assert.ok(!box.portalSetupConsentGate_().html.includes('1. Allow'));url='javascript:alert(1)';assert.ok(!box.portalSetupConsentGate_().html.includes('javascript:'))});
test('Granted consent allows setup to continue',()=>{required=false;assert.equal(box.portalSetupConsentGate_(),null)});
test('Gate executes before setup mutation',()=>{const s=fs.readFileSync(path.join(root,'backend/TrackerSync.gs'),'utf8');assert.ok(s.indexOf('const consentPage = portalSetupConsentGate_()')<s.indexOf('const result = setupPortalLiveSync()'));assert.ok(s.includes('if(consentPage)return consentPage;'))});
console.log(`${n} consent tests passed.`);
